language: generic
sudo: required # Super level priv
services: 
    - docker

before_install:
    - docker build -t zanebclark/docker-react -f Dockerfile.dev . # Tag only used inside of testing process

script: 
    - docker run -e CI=true zanebclark/docker-react npm run test -- --coverage # Two sets of dashes on purpose.