# ----------------------------------------------------------------------------
# Github Action Workflow to Deploy Node JS/Docker App to AWS Elastic Beanstalk
#
# Version                 Date                  Info
# 1.0                     12/26/2019            Initial Version
#
# Made by Zane Clark
# ----------------------------------------------------------------------------
name: CI-Pipeline-to-AWS-ElasticBeanstalk

on:
  push:
    branches:
      - master

env:
  EB_PACKAGE_S3_BUCKET_NAME : "elasticbeanstalk-us-east-1-057283593447"
  EB_APPLICATION_NAME       : "docker-react"
  EB_ENVIRONMENT_NAME       : "DockerReact-env"
  DEPLOY_PACKAGE_NAME       : "docker-react-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"

jobs:
  my_ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repository 
        uses: actions/checkout@v1

      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
      - name: Copy our deployment package to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_SECRET_KEY }}
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

      
      - name: Print a nice message upon completion
        run: echo "CI Pipeline Complete"